"""Initial migration

Revision ID: 3b423d51f2d8
Create Date: 2023-04-27 19:47:49.841496

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b423d51f2d8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("arch", sa.String(length=10), nullable=False),
        sa.Column("debuginfo", sa.Boolean(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("repomd_etag", sa.Text(), nullable=True),
        sa.Column("repomd_checksum", sa.Text(), nullable=True),
        sa.Column("check_ts", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "check_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("check_result_checksum", sa.Text(), nullable=True),
        sa.Column("is_old", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "old_repositories_mapping",
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("old_repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["old_repository_id"],
            ["repositories.id"],
            name="old_repositories_mapping_old_repository_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name="old_repositories_mapping_repository_id_fkey",
        ),
        sa.PrimaryKeyConstraint("repository_id", "old_repository_id"),
    )
    op.create_table(
        "update_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Text(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("update_records")
    op.drop_table("old_repositories_mapping")
    op.drop_table("repositories")
    # ### end Alembic commands ###
