"""Initial migration

Revision ID: 85af9fba3d4c
Create Date: 2023-04-18 16:24:46.954580

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "85af9fba3d4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("arch", sa.String(length=10), nullable=False),
        sa.Column("debuginfo", sa.Boolean(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("repomd_etag", sa.Text(), nullable=True),
        sa.Column("repomd_checksum", sa.Text(), nullable=True),
        sa.Column("check_ts", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "check_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "update_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Text(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("update_records")
    op.drop_table("repositories")
    # ### end Alembic commands ###
