"""Add old_repositories

Revision ID: fa0c72abb159
Revises: 4d38bf595bd5
Create Date: 2023-04-24 11:37:18.756524

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa0c72abb159"
down_revision = "4d38bf595bd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "old_repositories_mapping",
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("old_repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["old_repository_id"],
            ["repositories.id"],
            name="old_repositories_mapping_old_repository_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name="old_repositories_mapping_repository_id_fkey",
        ),
        sa.PrimaryKeyConstraint("repository_id", "old_repository_id"),
    )
    op.add_column(
        "repositories", sa.Column("is_old", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "is_old")
    op.drop_table("old_repositories_mapping")
    # ### end Alembic commands ###
